[package]
name = "cgol"
license-file = "LICENSE.txt"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
crossterm = "0.27.0"
rand = "0.8.5"
termion = "4.0.2"

[[bench]]
name = "cgol_benchmark"
harness = false
